#设置Tomcat端口
server:
  port: 8090


#链接数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lara1?serverTimezone=Asia/Shanghai
    name: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true

#配置MyBatis
mybatis:
  type-aliases-package: com.example.risk_judge_java.entity #别名
  mapper-locations: classpath:/mapper/*.xml #xml文件

#配置日志
logging:
  file:
    name: log/log.log
  level:
    root: info
    com.example.risk_judge_java: debug

